name: Build python application on release

on:
  release:
    types: [published]

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  apk:
    name: Generate build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
    - name: create executables with pyinstaller
      run: |
        pyinstaller cleanup_mod.spec
    - name: Release executables
      uses: softprops/action-gh-release@v1
      with:
        files: dist/cleanup_mod.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
