name: Build python application on release

on:
  release:
    types: [published]

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  apk:
    name: Generate build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build cleanup
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: .
        spec: cleanup_mod.spec
    - name: Release cleanup
      uses: softprops/action-gh-release@v1
      with:
        files: dist/windows/cleanup_mod.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Build find duplicate
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: .
        spec: find_duplicate_mod.spec
    - name: Release find duplicate
      uses: softprops/action-gh-release@v1
      with:
        files: dist/windows/find_duplicate_mod.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
